### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Parsa2820** [Parsa2820/es-project#1]
- [x] Web App (@rerfan24  - @kahbodaeini)
  - [x] Front-end
  - [x] Back-end
- [x] Water Level Sensor (@rerfan24 - @kahbodaeini)
  - [x] Software Implementation
  - [x] Raspberry Connection
  - [x] Write Data to File Periodically 
- [x] Distance Sensor (@Parsa2820 - @iTskAsra)
  - [x] Software Implementation
- [x] Actuator (@Parsa2820 - @iTskAsra)
  - [x] Physical Coleman System
  - [x] Stepper Motor Software Implementation
- [x] Integration

**Comment by iTskAsra** [comment]
**SEXOL**
